155 - On Fedora, fedora-domainname is used.
Addressing
[enable fedora-domainname.service]
[restart fedora-domainname.service]

Traceback (most recent call last):
  File "/usr/sbin/ipa-client-install", line 2918, in <module>
    sys.exit(main())
  File "/usr/sbin/ipa-client-install", line 2899, in main
    rval = install(options, env, fstore, statestore)
  File "/usr/sbin/ipa-client-install", line 2863, in install
    configure_nisdomain(options=options, domain=cli_domain)
  File "/usr/sbin/ipa-client-install", line 1481, in configure_nisdomain
    services.knownservices.domainname.restart()
  File "/usr/lib/python2.7/site-packages/ipaplatform/base/services.py", line 290, in restart
    capture_output=capture_output)
  File "/usr/lib/python2.7/site-packages/ipapython/ipautil.py", line 356, in run
    raise CalledProcessError(p.returncode, arg_string, stdout)
subprocess.CalledProcessError: Command ''/bin/systemctl' 'restart' 'fedora-domainname.service'' returned non-zero exit status 2